### PR TITLE
add pixel drawing

### PR DESCRIPTION
**Pull request by not-nullptr**

### CODE REVIEW

**Comment by shdrs** [comment]
@not-nullptr Hey thanks for the PR!
It looks like you used an autoformatter ([prettier](https://prettier.io/)?) - please revert your commit, then re-add your changes without the autoformatting ☺️ It's hard to review changes when all the formatting got changed and i would prefer the formatting to not be changed anyway.

Also - can you replace `"importsNotUsedAsValues": "error"` with `"verbatimModuleSyntax": true` instead of only removing it from `jsconfig.json`? 😎 [Source](https://stackoverflow.com/questions/75969776/option-importsnotusedasvalues-is-deprecated)

**Comment by shdrs** [comment]
@not-nullptr  Also - make sure this isn't implemented on `shelly`. Instead it should be implemented on `window.grid`, so that players can call `grid.drawPixel`, it makes more sense. Then you can also add it to the interactive documentation, that way players can call `list(grid)` and read about this function you added ☺️☀️ There is info about `list()` in the README.md instructions.

**Comment by not-nullptr** [comment]
> @not-nullptr Also - make sure this isn't implemented on `shelly`. Instead it should be implemented on `window.grid`, so that players can call `grid.drawPixel`, it makes more sense. Then you can also add it to the interactive documentation, that way players can call `list(grid)` and read about this function you added ☺️☀️ There is info about `list()` in the README.md instructions.

ah sorry. can you tell i don't know too much about this project? lol

**Comment by not-nullptr** [comment]
i'm gna open another pr on a seperate repo. no point dealing with merge requests when i've only ended up changing a single file

**Pull request closed without merging**
